// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestApi.Model;

namespace RestApi.Migrations
{
    [DbContext(typeof(ReservaEntities))]
    partial class ReservaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RestApi.Model.Clientes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellido");

                    b.Property<string>("Nombre");

                    b.Property<int>("NroDocumento");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("RestApi.Model.Reserva", b =>
                {
                    b.Property<string>("CodigoReserva")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Costo");

                    b.Property<DateTime>("FechaReserva");

                    b.Property<int>("IdCiudad");

                    b.Property<int>("IdCliente");

                    b.Property<int>("IdPais");

                    b.Property<int>("IdVehiculoCiudad");

                    b.Property<int>("IdVendedor");

                    b.Property<int>("PrecioVenta");

                    b.HasKey("CodigoReserva");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("RestApi.Model.Vendedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre");

                    b.HasKey("Id");

                    b.ToTable("Vendedor");
                });
#pragma warning restore 612, 618
        }
    }
}
